# Autogenerated wrapper script for libwebm_jll for i686-w64-mingw32-cxx11
export libwebm, webm2pes, webm2ts, webm_info

JLLWrappers.@generate_wrapper_header("libwebm")
JLLWrappers.@declare_library_product(libwebm, "libwebm.dll")
JLLWrappers.@declare_executable_product(webm2pes)
JLLWrappers.@declare_executable_product(webm2ts)
JLLWrappers.@declare_executable_product(webm_info)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libwebm,
        "bin\\libwebm.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        webm2pes,
        "bin\\webm2pes.exe",
    )

    JLLWrappers.@init_executable_product(
        webm2ts,
        "bin\\webm2ts.exe",
    )

    JLLWrappers.@init_executable_product(
        webm_info,
        "bin\\webm_info.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
